"""add product system models

Revision ID: fd9943ece7a0
Revises: 25506bfc72dc
Create Date: 2026-05-26 23:45:36.074931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9943ece7a0'
down_revision: Union[str, Sequence[str], None] = '25506bfc72dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('normalized_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_products_id'), 'normalized_products', ['id'], unique=False)
    op.create_index(op.f('ix_normalized_products_name'), 'normalized_products', ['name'], unique=False)
    op.create_index(op.f('ix_normalized_products_slug'), 'normalized_products', ['slug'], unique=True)
    op.create_table('platform_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('BLINKIT', 'ZEPTO', 'INSTAMART', 'BIGBASKET', 'FLIPKART', 'AMAZON', name='platformenum'), nullable=False),
    sa.Column('platform_product_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('product_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('normalized_product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['normalized_product_id'], ['normalized_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_products_id'), 'platform_products', ['id'], unique=False)
    op.create_index(op.f('ix_platform_products_platform'), 'platform_products', ['platform'], unique=False)
    op.create_index(op.f('ix_platform_products_platform_product_id'), 'platform_products', ['platform_product_id'], unique=False)
    op.create_table('product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('mrp', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('platform_product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_product_id'], ['platform_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_prices_id'), 'product_prices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_prices_id'), table_name='product_prices')
    op.drop_table('product_prices')
    op.drop_index(op.f('ix_platform_products_platform_product_id'), table_name='platform_products')
    op.drop_index(op.f('ix_platform_products_platform'), table_name='platform_products')
    op.drop_index(op.f('ix_platform_products_id'), table_name='platform_products')
    op.drop_table('platform_products')
    op.drop_index(op.f('ix_normalized_products_slug'), table_name='normalized_products')
    op.drop_index(op.f('ix_normalized_products_name'), table_name='normalized_products')
    op.drop_index(op.f('ix_normalized_products_id'), table_name='normalized_products')
    op.drop_table('normalized_products')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
